
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: access-control
data:
  HTTP_ADDR_ACCESS: ":8080"
  HTTP_ADDR_ADMIN: ":8081"
  HTTP_ADDR_REPORT: ":8082"
  KAFKA_TOPIC_INOUT: "inout-events"
  KAFKA_TOPIC_PERMISSION: "permission-events"
  KAFKA_GROUP_AGGREGATION: "aggregation-workers"
  KAFKA_GROUP_CACHE: "cache-invalidation-workers"
  CLICKHOUSE_USER: "default"
  KAFKA_BROKERS: "kafka:9092"
  REDIS_ADDR: "10.140.0.3:6379"
  REDIS_CLUSTER: "true"
  CLICKHOUSE_ADDR: "${CLICKHOUSE_ADDR}"
  API_KEY: "dev-api-key-2026"
  RATE_LIMIT_RPS_ACCESS: "100"
  RATE_LIMIT_RPS_ADMIN: "20"
  RATE_LIMIT_RPS_REPORT: "50"

