apiVersion: apps/v1
kind: Deployment
metadata:
  name: access-api
  namespace: access-control
  labels:
    app: access-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: access-api
  template:
    metadata:
      labels:
        app: access-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: access-api
        image: asia-east1-docker.pkg.dev/access-api-497314/access-api-repo/access-api:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 1000m
            memory: 256Mi
        env:
        - name: HTTP_ADDR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: HTTP_ADDR_ACCESS
        - name: REDIS_ADDR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_ADDR
        - name: REDIS_CLUSTER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_CLUSTER
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_BROKERS
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_TOPIC_INOUT
        - name: CLICKHOUSE_ADDR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: CLICKHOUSE_ADDR
        - name: CLICKHOUSE_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: CLICKHOUSE_USER
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CLICKHOUSE_PASSWORD
        - name: API_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: API_KEY
        - name: RATE_LIMIT_RPS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RATE_LIMIT_RPS_ACCESS
        - name: OUTBOX_DIR
          value: /tmp/outbox

        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: access-api
  namespace: access-control
spec:
  selector:
    app: access-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: access-api-hpa
  namespace: access-control
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: access-api
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
